services:
  db-app:
    container_name: db-app_container
    image: db-app:v1.0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
  
  writer-app:
    container_name: writer-app_container
    image: writer-app:v1.0
    ports:
      - "8080:5000"
    restart: on-failure:4

  reader-app:
    container_name: reader-app_container
    image: reader-app:v1.0
    ports:
      - "8081:5001"
    restart: unless-stopped


# docker compose up --build 'writer-app'